apiVersion: v2
name: agent
description: A Helm chart for KubeSphere-Extension DevOps agent(backend)
type: application
version: 1.0.0
appVersion: v4.0.0
home: https://www.kubesphere.io/devops/
sources:
  - https://github.com/kubesphere/ks-devops
  - https://github.com/kubesphere-sigs/ks-devops-helm-chart
annotations:
  extensions.kubesphere.io/devops: agent
dependencies: {}