apiVersion: v1
kind: Service
metadata:
  name: storageclass-accessor
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    {{- include "storageclass-accessor.selectorLabels" . | nindent 4 }}
  ports:
    - protocol: TCP
      port: 443
      targetPort: 443