---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: snapshot-controller
  namespace: {{ default .Release.Namespace .Values.namespace }}
  labels:
    app: snapshot-controller
spec:
  serviceName: "snapshot-controller"
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: snapshot-controller
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app: snapshot-controller
    spec:
      serviceAccount: {{ .Values.serviceAccount.name }}
      containers:
        - name: snapshot-controller
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          args:
            - "--v=5"
            - "--leader-election=false"
          imagePullPolicy: {{ .Values.image.pullPolicy}}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
