{{- if (and .Values.installCRDS (not (.Capabilities.APIVersions.Has "mysql.radondb.com/v1alpha1"))) }}
{{- if and .Values.installCRDS -}}
{{- range $path, $bytes := .Files.Glob "crds/*.yaml" }}
---
{{ $.Files.Get $path }}
{{- end }}
{{- end }}
{{- end }}
